#!/usr/bin/env bash
# One command to a working inbox.
#
#   ./bootstrap.sh            demo mode — seeded mailbox, no Resend account needed
#   ./bootstrap.sh live       real mode — asks for a Resend API key and a domain
#   ./bootstrap.sh stop       stop both processes
#   ./bootstrap.sh status     show what is running
#
# Everything lands in ./.webmail (binaries, database, env, logs, pids); delete
# that directory and it is as if this never ran.
set -euo pipefail
cd "$(dirname "$0")"

ROOT="$PWD/.webmail"
BIN="$ROOT/bin"
ENV_FILE="$ROOT/webmail.env"
POCHE_PORT="${POCHE_PORT:-17781}"
UI_PORT="${UI_PORT:-3090}"

POCHE_REPO="javimosch/poche"
WEBMAIL_REPO="javimosch/poche-resend-webmail"

say()  { printf '\033[36m%s\033[0m\n' "$*"; }
warn() { printf '\033[33m%s\033[0m\n' "$*" >&2; }
die()  { printf '\033[31m%s\033[0m\n' "$*" >&2; exit 1; }

detect_target() {
  local os arch
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"
  case "$arch" in
    x86_64|amd64) arch=amd64 ;;
    aarch64|arm64) arch=arm64 ;;
    *) die "unsupported architecture: $arch" ;;
  esac
  echo "${os}-${arch}"
}

download() { # url dest
  curl -fsSL -m 300 "$1" -o "$2" || die "download failed: $1"
  chmod +x "$2"
}

# A downloaded binary that crashes on first use is worse than a missing one:
# the failure surfaces three steps later as something unrelated.
verify_poche() {
  local probe; probe="$(mktemp -d)"
  if ! POCHE_DB="$probe/db" POCHE_NO_NUDGE=1 FEEDBACK_RELAY=off "$BIN/poche" init >/dev/null 2>&1; then
    rm -rf "$probe"
    cat >&2 <<EOF

The poche binary that was downloaded does not run on this machine
($BIN/poche exits non-zero on 'init').

The published linux-amd64 artifact for poche v0.3.0 is known to crash with a
floating point exception on some hosts. Build it from source and point this
script at your build:

  git clone https://github.com/$POCHE_REPO && cd poche && ./build.sh
  POCHE_BIN=\$PWD/poche $0 ${1:-demo}

EOF
    exit 1
  fi
  rm -rf "$probe"
}

fetch_binaries() {
  local target; target="$(detect_target)"
  mkdir -p "$BIN"
  # Let people supply their own builds — useful on platforms without a release
  # artifact, and the escape hatch when a published one is broken.
  if [[ -n "${POCHE_BIN:-}" ]]; then
    say "→ using POCHE_BIN=$POCHE_BIN"
    install -m 755 "$POCHE_BIN" "$BIN/poche"
  fi
  if [[ -n "${WEBMAIL_BIN:-}" ]]; then
    say "→ using WEBMAIL_BIN=$WEBMAIL_BIN"
    install -m 755 "$WEBMAIL_BIN" "$BIN/poche-resend-webmail"
  fi
  if [[ ! -x "$BIN/poche" ]]; then
    # poche currently ships linux/amd64 only; build from source for anything else.
    if [[ "$target" != "linux-amd64" ]]; then
      die "poche publishes linux-amd64 binaries only — build it from https://github.com/$POCHE_REPO for $target and place it at $BIN/poche"
    fi
    say "→ fetching poche (store)"
    download "https://github.com/$POCHE_REPO/releases/latest/download/poche-linux-amd64" "$BIN/poche"
  fi
  if [[ ! -x "$BIN/poche-resend-webmail" ]]; then
    say "→ fetching poche-resend-webmail (${target})"
    download "https://github.com/$WEBMAIL_REPO/releases/latest/download/poche-resend-webmail-${target}" "$BIN/poche-resend-webmail"
  fi
  verify_poche "${1:-demo}"
}

port_busy() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null && { exec 3>&-; return 0; } || return 1; }

random_hex() { head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

write_env() { # mode [resend_key] [from_domain]
  local mode="$1" key="${2:-}" domain="${3:-}"
  cat > "$ENV_FILE" <<EOF
# generated by bootstrap.sh — keep this file private
POCHE_URL=http://127.0.0.1:$POCHE_PORT
POCHE_TOKEN=$POCHE_TOKEN
POCHE_DB=$ROOT/poche.data
POCHE_NO_NUDGE=1
FEEDBACK_RELAY=off

WEBMAIL_TOKEN=$(random_hex)
ADMIN_TOKEN=$(random_hex)
# encrypts per-mailbox Resend credentials at rest — losing it means re-entering them
CREDENTIALS_KEY=$(random_hex)
BLOB_DIR=$ROOT/blobs

PORT=$UI_PORT
WEBMAIL_URL=http://127.0.0.1:$UI_PORT
BRAND_NAME=poche
EOF
  if [[ "$mode" == "live" ]]; then
    cat >> "$ENV_FILE" <<EOF
RESEND_API_KEY=$key
MAIL_FROM_ALLOWLIST=@$domain
EOF
  fi
  chmod 600 "$ENV_FILE"
}

start_stack() {
  mkdir -p "$ROOT"
  set -a; . "$ENV_FILE"; set +a

  if port_busy "$POCHE_PORT"; then die "port $POCHE_PORT is in use — set POCHE_PORT to something free"; fi
  if port_busy "$UI_PORT";   then die "port $UI_PORT is in use — set UI_PORT to something free"; fi

  say "→ starting poche on :$POCHE_PORT"
  nohup "$BIN/poche" serve "$POCHE_PORT" >"$ROOT/poche.log" 2>&1 &
  echo $! > "$ROOT/poche.pid"

  # the store needs to answer before the BFF asks it for a schema
  for _ in $(seq 1 40); do
    curl -fsS -m 2 "http://127.0.0.1:$POCHE_PORT/health" >/dev/null 2>&1 && break
    sleep 0.25
  done
  curl -fsS -m 2 "http://127.0.0.1:$POCHE_PORT/health" >/dev/null 2>&1 || {
    tail -5 "$ROOT/poche.log" >&2; die "poche did not come up — see $ROOT/poche.log"
  }

  say "→ starting webmail on :$UI_PORT"
  nohup "$BIN/poche-resend-webmail" serve -port "$UI_PORT" >"$ROOT/webmail.log" 2>&1 &
  echo $! > "$ROOT/webmail.pid"

  for _ in $(seq 1 40); do
    curl -fsS -m 2 "http://127.0.0.1:$UI_PORT/api/health" >/dev/null 2>&1 && break
    sleep 0.25
  done
  curl -fsS -m 2 "http://127.0.0.1:$UI_PORT/api/health" >/dev/null 2>&1 || {
    tail -5 "$ROOT/webmail.log" >&2; die "webmail did not come up — see $ROOT/webmail.log"
  }
}

cmd_stop() {
  local stopped=0
  for name in webmail poche; do
    if [[ -f "$ROOT/$name.pid" ]] && kill -0 "$(cat "$ROOT/$name.pid")" 2>/dev/null; then
      kill "$(cat "$ROOT/$name.pid")" 2>/dev/null || true
      stopped=1
    fi
    rm -f "$ROOT/$name.pid"
  done
  [[ $stopped == 1 ]] && say "stopped." || say "nothing was running."
}

cmd_status() {
  for name in poche webmail; do
    if [[ -f "$ROOT/$name.pid" ]] && kill -0 "$(cat "$ROOT/$name.pid")" 2>/dev/null; then
      printf '  %-8s running (pid %s)\n' "$name" "$(cat "$ROOT/$name.pid")"
    else
      printf '  %-8s stopped\n' "$name"
    fi
  done
}

cmd_up() { # mode
  local mode="$1"
  mkdir -p "$ROOT"
  fetch_binaries "$mode"

  if [[ ! -f "$ENV_FILE" ]]; then
    say "→ initialising the store"
    POCHE_DB="$ROOT/poche.data" POCHE_NO_NUDGE=1 FEEDBACK_RELAY=off \
      "$BIN/poche" init > "$ROOT/init.json" 2>/dev/null || die "poche init failed"
    POCHE_TOKEN="$(sed -n 's/.*"admin_token":"\([^"]*\)".*/\1/p' "$ROOT/init.json")"
    [[ -n "$POCHE_TOKEN" ]] || die "could not read the admin token from poche init"

    local key="" domain=""
    if [[ "$mode" == "live" ]]; then
      read -r -p "Resend API key (re_…): " key
      [[ -n "$key" ]] || die "a Resend API key is required for live mode"
      read -r -p "Domain you send from (e.g. example.com): " domain
      [[ -n "$domain" ]] || die "a sending domain is required for live mode"
    fi
    write_env "$mode" "$key" "$domain"
  else
    say "→ reusing $ENV_FILE"
  fi

  start_stack
  set -a; . "$ENV_FILE"; set +a

  if [[ "$mode" == "demo" ]]; then
    if [[ "$("$BIN/poche-resend-webmail" list -limit 1 2>/dev/null | grep -c '"items"')" == "1" ]]; then
      "$BIN/poche-resend-webmail" seed -count 25 >/dev/null 2>&1 || true
    fi
  fi

  echo
  say "inbox ready → http://127.0.0.1:$UI_PORT/?token=$WEBMAIL_TOKEN"
  echo
  if [[ "$mode" == "demo" ]]; then
    cat <<EOF
This is demo mode: 25 fake messages, no Resend account, nothing can be sent.
For a real mailbox:

  ./bootstrap.sh stop && rm -rf .webmail && ./bootstrap.sh live

EOF
  else
    cat <<EOF
Live mode. To create a mailbox someone can log into:

  set -a; . $ENV_FILE; set +a
  $BIN/poche-resend-webmail mailbox create \\
    --address you@yourdomain.com --password - \\
    --recovery-email backup@elsewhere.com

Then point a Resend webhook (event: email.received) at:

  http://<this-host>:$UI_PORT/webhooks/resend

and put its signing secret on the mailbox:

  printf 'whsec_…' | $BIN/poche-resend-webmail mailbox update \\
    --address you@yourdomain.com --resend-webhook-secret -

EOF
  fi
  echo "logs: $ROOT/webmail.log · $ROOT/poche.log"
  echo "stop: ./bootstrap.sh stop"
}

case "${1:-demo}" in
  demo) cmd_up demo ;;
  live) cmd_up live ;;
  stop) cmd_stop ;;
  status) cmd_status ;;
  *) die "usage: ./bootstrap.sh [demo|live|stop|status]" ;;
esac
